mysql:
  host: '127.0.0.1'
  port: 3306
  database: demodb
  username: 'root'
  password: 'root123456'
spring:
  datasource:
    url: "jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=true"
    username: root
    password: ${mysql.password}
---
spring:
  profiles: default
mysql:
  host: 127.0.0.1
  database: demodb
---
spring:
  profiles: dev
mysql:
  host: mysql-dev
  database: demodb_dev
---
spring:
  profiles: prod
mysql:
  host: mysql-prod
  database: demodb_prod
---
spring:
  profiles: test
mysql:
  host: mysql-test
  database: demodb_test