server:
  port: 9999
swagger:
  oauth:
    base-url:  http://127.0.0.1:8001
    client-id: demo_client
    client-secret: demo_secret
eureka:
  client:
    service-url:
      defaultZone: http://discovery:3GfhPZQifTpVcu@127.0.0.1:8761/eureka