server:
  port: 8002
swagger:
  oauth:
    base-url:  http://127.0.0.1:8001
    client-id: demo_client
    client-secret: demo_secret
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3316/spring_cloud_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull"
    username: "root"
    password: "root123456"
security:
  headers:
    frame: false
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAieQ9BML07B1ahs/PwL0f2UmvyGDbLjSU7//ZZ5UoQjpm4gBeJ0bFYLN4CK++ao7XYjZ4B2Rwu81cZ3zQ7RI7qtxGwTMFyavkTrarVfurcmwfS5vyyEChEiYDWEvi+bGurZasZKrXZ1r1VFLk+TRQfunQwRCIYGP+e3qZ2SiuaOqqdEjYia3CmKcM4QhN15CO+Dv7NclKRspN0VmntF4hyfkruV81gHnTXzZQ0NusWxs+yrLtpKot7kROGfVkDEpGPWUBXyUQLr5gCBVnzpTLBYCTjfYh+nzIpKfjjHLgW9Gy74WCpYLRY24u/KZzPecHZxnlJZ43VTUL4Gh7hlIeeQIDAQAB
          -----END PUBLIC KEY-----
eureka:
  client:
    service-url:
      defaultZone: http://discovery:3GfhPZQifTpVcu@$127.0.0.1:8761/eureka