server:
  port: 8001
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/spring_cloud_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull"
    username: "root"
    password: "root123456"
oauth2:
  private-key:
    path: "jwt_keypair.jks"
    alias: "jwt"
    password: "KCPzQVp8VVyHV9Ds"