server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://rm-2zex5iy686n21e940.mysql.rds.aliyuncs.com/spring_cloud_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull"
    username: "demo"
    password: "Hbhu7uuMZ6noDenh"
oauth2:
  private-key:
    path: "jwt_keypair.jks"
    alias: "jwt"
    password: "KCPzQVp8VVyHV9Ds"